- name: "Web Browser"
  description: "Choose your default browser"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - chromium
    - firefox
    - opera
    - brave
    
- name: "Communication"
  description: "Communication apps"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - slack-web-jak
    - skype-web-jak
    - whatsapp-web-jak
    - telegram-desktop
    - discord
    
- name: "Office"
  description: "Choose a office suite"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - calligra
    - libreoffice-fresh
    - microsoft-office-web-jak
    - freeoffice
    
- name: "Steam"
  description: "Steam Goodies"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - steam-manjaro
    - linux-steam-integration
    - game-devices-udev

- name: "Design"
  description: "Design Software"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - inkscape
    - gimp
    - fontforge
    - mypaint

- name: "Video Edit"
  description: "Video Editing Software"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - pitivi
    - openshot
    - kdenlive

- name: "Development"
  description: "Development Software"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - atom
    - code
    - meld
    - pycharm-community-edition

- name: "Virtualization"
  description: "Virtualbox"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-headers

- name: "Base Defaults"
  description: "Leave it as it is if you not sure"
  critical: false
  hidden: true
  selected: true
  expanded: false
  packages:
    ## Connect Packages
    - android-tools
    - android-udev
    - gvfs
    - gvfs-google
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - mtpfs
    - udiskie
    - udisks2
    ## Libraries for Sound/Audio/Video
    - ffmpeg
    - grilo-plugins
    - gst-libav
    - gst-plugins-bad
    - gst-plugins-base
    - gst-plugins-good
    - gst-plugins-ugly
    - libdvdcss
    # Applications
    - nautilus-admin
    - nautilus-empty-file
    - dconf-editor
    - lxrandr
    - vlc
    - lightdm-gtk-greeter-settings
    - gufw
    - deja-dup
    - syncthing-gtk
    - hardinfo
    - gthumb
    - evince
    - geary
    - gedit
    - file-roller
    ## Startup and shutdown
    - bootsplash-systemd
    - bootsplash-theme-manjaro
    # Base
    - xf86-input-wacom #support for tablet and pen display ( wacom ecc. )
    - manjaro-settings-manager-notifier
    - mousetweaks
    - nss-mdns
    - numlockx
    - powertop
    - inxi
    - dunst-notify-speech
    - dmidecode
    - gtkhash-nautilus
    - fprintd #need for finger id reader
    - lxqt-powermanagement
    - blueberry
    - usb_modeswitch
    - openssh
    - manjaro-browser-settings
    # Extra depends for file-roller
    - gnome-getting-started-docs
    - p7zip
    - unrar
    - unace
    - lrzip
    - gtk3-print-backends
    - manjaro-documentation-en
    - manjaro-printer
    - simple-scan 
    - ffmpegthumbnailer
    - kernel-alive
    ## Package management
    - snapd
    - snapd-glib
    - pamac-snap-plugin
    - pamac-flatpak-plugin
    - apparmor